---

- hosts: db-servers

  tasks:

  - name: Set authorized key taken from file
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: Install prerequisites
    apt: 
      name: "{{item}}"
      state: latest
    with_items:
      - sshpass

  - name: Add user
    user:
      name: "{{ dbuser }}"
      group: postgres
      create_home: no
      state: present

  - name: Change user's home dir
    user:
      name: "{{ dbuser }}"
      home: /home/{{ dbuser }}/data/
      generate_ssh_key: yes

  - name: Get Ubuntu version
    shell: lsb_release -cs
    args:
      executable: /bin/bash
    register: ubuntu_version


  - name: ubuntu | add PostgreSQL repository
#    apt_repository: repo=deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main 
# Add specified repository into sources list using specified filename.
    apt_repository:
#!!!!
      repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_version.stdout }}-pgdg main
      state: present
      filename: postgres

  - name: Add an Apt signing key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present

  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: PostgreSQL install
    apt: pkg={{ item }}
    with_items:
    - postgresql-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - postgresql-contrib-{{ pg_contrib_version }}
    - libpq-dev
    - python-psycopg2
    register: db_setup
#      state: present
#      become: yes

#   - name: Setup postgres cluster to default to utf8 | stop cluster
  # if the dbs haven't been created yet, we want to destroy the whole db
  # cluster and recreate it with proper utf8 support.
#    become_user: postgres
#  shell: pg_dropcluster --stop {{ pg_version }} main
#  when: db_setup.changed and pg_recreate_cluster # only do this if the dbs haven't been created yet

#   - name: Setup postgres cluster to default to utf8 | start cluster
  # if the dbs haven't been created yet, we want to destroy the whole db
  # cluster and recreate it with proper utf8 support. From http://ph.ly/pg
#    become_user: postgres
#    shell: pg_createcluster --start -e {{ pg_encoding }} {{ pg_version }} main
#     when: db_setup.changed and pg_recreate_cluster # only do this if the dbs haven't been created yet

  - name: ensure postgresql server is started
    service: name=postgresql state=started enabled=yes arguments={{ pg_version }} pattern="/{{ pg_version }}/.*/postgres"

  - name: Create a database
    postgresql_db:
      name: "{{ dbname }}"
    become_user: postgres
    
  - name: Create user, and grant access to database
    postgresql_user:
      db: "{{ dbname }}"
      name: "{{ dbuser }}"
      password: "{{ dbpassword }}"
      encrypted: yes
      role_attr_flags: "{{ role_attr }}"
#      priv: "{{ privileges }}"
    become_user: postgres

