---

- name: Create an Jenkins Docker container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    published_ports: "{{ docker_pub_ports }}"
    volumes: 
      - /home/{{ ansible_env.SUDO_USER }}/jenkins:/var/jenkins_home
      # - /home/{{ lookup('env','USER') }}:/var/jenkins_home
    pull: yes
