---

- name: Install pip
  apt:
    name: python-pip
    update_cache: yes

- name: Install Python dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - urllib3
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1
    - docker-py
  # state: latest
    # - "{{ python_version }}"

- name: Install packages to allow apt to use a repository over HTTPS
  apt: 
    # update_cache: yes
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - gnupg-curl
    - libseccomp2


- name: Add a Docker GPG key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  # url: https://download.docker.com/linux/ubuntu/gpg

# - name: Update cache
#   apt: 
#     update_cache: yes    

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker

- name: Install Docker
  apt: 
    name: docker-ce={{ docker_version }}
  # with_items:
    # - docker-ce
    # - docker-ce-cli 
    # - containerd.io
  # register: docker
  # update_cache: yes


# - name: Add current user to docker group
#   user:
#     name: "{{ current_user.stdout }}"
#     # name: "{{ ansible_env.USERNAME }}"
#     groups: docker

- name: Create an nginx Docker container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    published_ports: "{{ docker_pub_ports }}"
    pull: yes
